"""Generate phone-pwa/js/bank.js from the canonical question bank.

Usage:  python tools\build_bank_js.py

The PWA is fully client-side, so the 510-question bank is embedded as a
plain JS constant.  Regenerate this file after ANY bank change
(questions_complete.json at the mscert root is the source of truth),
then bump the cache version in sw.js.

The output is pure ASCII (ensure_ascii) so no server-side charset
mishandling can corrupt the payload.
"""

import json
import os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(BASE, "questions_complete.json")
DST = os.path.join(BASE, "phone-pwa", "js", "bank.js")


def main():
    with open(SRC, "r", encoding="utf-8") as fh:
        data = json.load(fh)
    qs = data["questions"]
    payload = ",\n".join(json.dumps(q, ensure_ascii=True, sort_keys=True,
                                    separators=(",", ":"))
                         for q in qs)
    out = (
        "// AUTO-GENERATED by tools\\build_bank_js.py - do not edit by hand.\n"
        "const BANK_COUNT = %d;\n"
        "const QUESTION_BANK = [\n%s\n];\n"
    ) % (len(qs), payload)
    os.makedirs(os.path.dirname(DST), exist_ok=True)
    with open(DST, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(out)
    print(f"bank.js: {len(qs)} questions -> {DST} "
          f"({os.path.getsize(DST)} bytes)")


if __name__ == "__main__":
    main()
